version: "3.8"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - static_volume:/app/static
    command: gunicorn
    ports:
      - "8000:8000"
    environment:
      -
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      -
volumes:
  static_volume:
